# MoFox-UI 配置文件

[server]
host = "127.0.0.1"
port = 3000

[logging]
level = "info"
file = "logs/mofox-ui.log"

[services]
# MaiBot 服务配置
[services.bot]
name = "MaiBot"
executable = "../Bot/main.py"
working_dir = "../Bot"
log_file = "../Bot/logs/bot.log"

# Adapter 服务配置
[services.adapter]
name = "Adapter"
executable = "../Adapter/main.py"
working_dir = "../Adapter"
log_file = "../Adapter/logs/adapter.log"

# Matcha-Adapter 服务配置
[services.matcha_adapter]
name = "Matcha-Adapter"
executable = "../Matcha-Adapter/main.py"
working_dir = "../Matcha-Adapter"
log_file = "../Matcha-Adapter/logs/matcha.log"

[update]
# 仓库更新配置（参考 onekey.py）
git_repos = [
    { name = "Bot", path = "../Bot", url = "https://github.com/MoFox-Studio/MaiBot-Plus" },
    { name = "Adapter", path = "../Adapter", url = "https://github.com/MoFox-Studio/Adapter" },
    { name = "Matcha-Adapter", path = "../Matcha-Adapter", url = "https://github.com/MoFox-Studio/Matcha-Adapter" }
]

[statistics]
# 统计数据配置
html_file = "../Bot/maibot_statistics.html"
refresh_interval = 5  # 秒
